pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - approved-reviews-by=favna
      - base=master
      - author: favware-bot
    actions:
      merge:
        method: squash