name: API Doc Generation

on:
  release:
    types: [published]

jobs:
  docgen:
    name: Automated API Doc Generation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.GITHUB_PAT }}
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install Deps
      run: yarn
    - name: Generate docs
      run: yarn docs
    - name: Commit changes
      run: |
        git config --local user.email "favwarebot@gmail.com"
        git config --local user.name "Favware-bot"
        git commit -sam "docs(api): automated api docs update"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}